### ISSUE TITLE
סכמה

### ISSUE THREAD

**Issue by gilgardosh** [Urigo/new-bank-poalim-scraper#4]
https://github.com/Urigo/new-bank-poalim-scraper/blob/bfbb752ab7e282308a3bbe1846f3cd054f0befe8/src/schemas/ILSCheckingTransactionsDataSchema.json#L9

הסכמה בנויה כרגע ככה:
{type: [everything else]}
ככה מתקבל אצלך המידע?

כנ"ל ForeignTransactionsSchema

**Comment by Urigo** [comment]
@gilgardosh yes that's how I get it.
Should we do a small meeting and compare results?

**Comment by Urigo** [comment]
fixed by https://github.com/Urigo/new-bank-poalim-scraper/pull/10
