### ISSUE TITLE
multiScrapers new branch issues

### ISSUE THREAD

**Issue by gilgardosh** [Urigo/new-bank-poalim-scraper#8]
on [this commit](https://github.com/Urigo/new-bank-poalim-scraper/commit/e8a49e8ad4885072d45eeca35a73b40b0dcb63f2),
make sure if **accountAgreementOpeningDate** field is required at accountDataSchema.json
(it is for me, but @Urigo  removed it)

**Comment by gilgardosh** [comment]
same for **beneficiaryDetailsData** at ILSCheckingTransactionsDataSchema.json
on [this commit](https://github.com/Urigo/new-bank-poalim-scraper/commit/1462b37f0aa4869380b574e2da1cfe013d07560f)

**Comment by Urigo** [comment]
fixed in https://github.com/Urigo/new-bank-poalim-scraper/pull/10
